import './header.css';
import logoPicture from './logo.png';

const header = document.createElement('header');
const nav = document.createElement('nav');
const logo = document.createElement('img');
logo.src = logoPicture;
logo.alt = 'logo';
const ul = document.createElement('ul');
const li1 = document.createElement('li');
const li2 = document.createElement('li');
const li3 = document.createElement('li');
const a1 = document.createElement('a');
const a2 = document.createElement('a');
const a3 = document.createElement('a');
a1.textContent = 'Об игре';
a1.href = '#startDiv';
a2.textContent = 'Геймплэй';
a2.href = '#gameplay';
a3.textContent = 'Об авторе';
a3.href = '#author';
li1.appendChild(a1);
li2.appendChild(a2);
li3.appendChild(a3);
ul.appendChild(li1);
ul.appendChild(li2);
ul.appendChild(li3);
nav.appendChild(ul);
header.appendChild(logo);
header.appendChild(nav);
export default header;
